### ISSUE TITLE
Version 0.1: make it work as intended

### ISSUE THREAD

**Issue by yogodoshi** [yogodoshi/cansei#11]
### Description
The `0.1` version will be a "just works™" version. It won't allow any configuration at all.

### To-do
- [x] Implement `User` model (validations, specs, etc)
- [x] setup omniauth/ omniauth-twitter (gem, action, routes, helpers, etc)
- [x] Implement log-out (route, action, specs)
- [x] Implement `Users#new` (which will be the unlogged in page, there is no #create as the user will be created through omniauth) 
- [x] Implement `Users#edit` (when the user is logged in)
- [x] Implement `Users#update` (to update the tweet preference)
- [x] Implement `TwitterService#tweet_to_the_company` with hardcoded texts, messages, company, etc
- [x] Implement rake task that calls `TwitterService#tweet_to_the_company` for each `User`
  - [x] create a rake task for each frequency and set it up accordingly on heroku so the user tweets at the intended frequency
- [x] handle the scenario where the user doesnt authorize the twitter log-in
- [x] Q&A back-end
- [x] Deploy

**Comment by yogodoshi** [comment]
It's aliiiive! 🎉
