### ISSUE TITLE
Version 0.2: make it configurable

### ISSUE THREAD

**Issue by yogodoshi** [yogodoshi/cansei#12]
### Description
People should be able to create their own website by simply:

1. clone the repo
1. change a yaml file
1. deploy to heroku
1. "just works™"

### To-do
- [x] find an easy way to allow non-programmers to config the app
  - [x] see if https://github.com/railsconfig/config works fine with heroku
- [x] allow people to change:
  - [x] explanation of how it works in `layouts/application`
  - [x] website title
  - [x] twitter handle of the company
  - [x] company name
  - [x] customize the random tweets list
- [x] remove the twitter messages that only works for banks, allow people to add their own through the settings file
- [x] Write tutorial in portuguese in the README explaining how to deploy your own
- [ ] Q&A whole process
