### ISSUE TITLE
Version 2.0: making companies better all around the world

### ISSUE THREAD

**Issue by yogodoshi** [yogodoshi/cansei#14]
### Description
Change everything to english so anyone in the world can use it. Also make almost every text on it configurable so people can use this project to complain to a Thai company if they deserve it 👍 

### To-do
- [ ] are we gonna keep localization files to make it even easier to people set up their website in any language?
- [ ] make sure the README is in english (keep the pt-br version as `README-pt` and link it in the english version)
- [ ] translate github's project description to english
- [ ] Q&A the whole process in a different language
