### ISSUE TITLE
Allow a custom domain name to be configured

### ISSUE THREAD

**Issue by yogodoshi** [yogodoshi/cansei#18]
Allow the user to easily set a custom domain.

### To-do
- [ ] implement it
- [ ] make it configurable through the settings vars
- [ ] add ENV var as canonical host
- [ ] explain how in the tutorial
